server:
  port: 8081

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/bookify
    username: postgres
    password: root

  servlet:
    multipart:
      max-file-size: 100000000
      max-request-size: 100000000

  flyway:
    out-of-order: true

  cache:
    redis:
      time-to-live: 1000s

jwt:
  secret-key: 294A404E635266556A586E327235753878214125442A472D4B6150645367566B
  duration: 3600000

